export const ADMIN_ROLE_PERMISSIONS: Record<string, string[]> = {
  SUPER_ADMIN: [
    'View users',
    'Edit users',
    'Delete users',
    'View transactions',
    'Process refunds',
    'View financial reports',
    'Manage financial settings',
    'View KYC requests',
    'Approve KYC',
    'Reject KYC',
    'Restrict users',
    'Unrestrict users',
    'Send KYC reminders',
    'Manage config',
    'View config',
    'View support tickets',
    'Respond to tickets',
    'Manage admins',
    'View admins',
    'View events',
    'Manage events',
    'View wallets',
    'Manage wallets',
    'View AML alerts',
    'Manage AML alerts',
    'View audit logs',
    'View withdrawals',
    'Manage withdrawals',
    'View notifications',
    'View dashboard',
  ],
  FINANCE_ADMIN: [
    'View users',
    'View transactions',
    'Process refunds',
    'View financial reports',
    'Manage financial settings',
    'View wallets',
    'View config',
    'View audit logs',
    'View withdrawals',
    'Manage withdrawals',
    'View dashboard',
  ],
  SUPPORT: [
    'View users',
    'View support tickets',
    'Respond to tickets',
    'Send KYC reminders',
    'View events',
    'View wallets',
    'View config',
    'View notifications',
    'View dashboard',
  ],
  COMPLIANCE: [
    'View users',
    'View KYC requests',
    'Approve KYC',
    'Reject KYC',
    'Restrict users',
    'Unrestrict users',
    'Send KYC reminders',
    'View transactions',
    'View financial reports',
    'View events',
    'View wallets',
    'View config',
    'View AML alerts',
    'Manage AML alerts',
    'View audit logs',
    'View withdrawals',
    'View notifications',
    'View dashboard',
  ],
  OPERATIONS: [
    'View users',
    'Edit users',
    'View transactions',
    'View financial reports',
    'View KYC requests',
    'Manage config',
    'View config',
    'View support tickets',
    'Respond to tickets',
    'View events',
    'Manage events',
    'View wallets',
    'Manage wallets',
    'View AML alerts',
    'View audit logs',
    'View withdrawals',
    'View notifications',
    'View dashboard',
  ],
  VIEW_ONLY: [
    'View users',
    'View transactions',
    'View financial reports',
    'View KYC requests',
    'View config',
    'View support tickets',
    'View events',
    'View wallets',
    'View AML alerts',
    'View audit logs',
    'View withdrawals',
    'View notifications',
    'View dashboard',
  ],
};

export const ROLE_DESCRIPTIONS: Record<string, string> = {
  SUPER_ADMIN: 'Full system access and control',
  OPERATIONS: 'Manage events, wallets, and day-to-day platform operations',
  COMPLIANCE: 'Manage KYC, AML alerts, and user compliance activities',
  SUPPORT: 'Handle user support and inquiries',
  FINANCE_ADMIN: 'Manage withdrawals, transactions, and financial reporting',
  VIEW_ONLY: 'Read-only access across the admin portal',
};
