export const AUDIT_ACTION_TYPE_OPTIONS = [
  { value: '', label: 'All action types' },
  { value: 'CONFIG_UPDATED', label: 'CONFIG_UPDATED' },
  { value: 'CONFIG_CREATED', label: 'CONFIG_CREATED' },
  { value: 'CONFIG_DEACTIVATED', label: 'CONFIG_DEACTIVATED' },
  { value: 'WALLET_INTERNAL_BALANCE_ADJUSTED', label: 'WALLET_INTERNAL_BALANCE_ADJUSTED' },
  { value: 'KYC_REMINDER_SENT', label: 'KYC_REMINDER_SENT' },
  { value: 'USER_RESTRICTED', label: 'USER_RESTRICTED' },
  { value: 'USER_UNRESTRICTED', label: 'USER_UNRESTRICTED' },
  { value: 'KYC_APPROVED', label: 'KYC_APPROVED' },
  { value: 'KYC_REJECTED', label: 'KYC_REJECTED' },
  { value: 'CUSTOMER_TIER3_APPROVED', label: 'CUSTOMER_TIER3_APPROVED' },
  { value: 'CUSTOMER_TIER3_REVERSED', label: 'CUSTOMER_TIER3_REVERSED' },
  { value: 'CUSTOMER_TIER3_COMPLETED', label: 'CUSTOMER_TIER3_COMPLETED' },
  { value: 'ADMIN_INVITED', label: 'ADMIN_INVITED' },
  { value: 'ADMIN_CREATED', label: 'ADMIN_CREATED' },
  { value: 'ADMIN_INVITE_CANCELLED', label: 'ADMIN_INVITE_CANCELLED' },
  { value: 'ADMIN_UPDATED', label: 'ADMIN_UPDATED' },
  { value: 'ADMIN_DEACTIVATED', label: 'ADMIN_DEACTIVATED' },
  { value: 'ADMIN_ROLE_ASSIGNED', label: 'ADMIN_ROLE_ASSIGNED' },
  { value: 'ADMIN_LOGIN', label: 'ADMIN_LOGIN' },
  { value: 'ADMIN_EXPORT', label: 'ADMIN_EXPORT' },
  { value: 'EVENT_SUSPENDED', label: 'EVENT_SUSPENDED' },
  { value: 'EVENT_DELETED', label: 'EVENT_DELETED' },
  { value: 'WITHDRAWAL_REJECTED', label: 'WITHDRAWAL_REJECTED' },
  { value: 'UTILITY_BILL_APPROVED', label: 'UTILITY_BILL_APPROVED' },
  { value: 'UTILITY_BILL_REJECTED', label: 'UTILITY_BILL_REJECTED' },
] as const;
